/* Timed Study Quiz — app logic
 * Questions live in questions.json (generated by scripts/build_questions.py).
 *
 * Question types:
 *   open  – written / calculation answer, self-marked against a mark scheme
 *   mcq   – multiple choice, auto-marked
 *   short – short typed answer (flashcards), auto-marked by fuzzy match
 */
(() => {
  'use strict';

  const DIFFICULTIES = ['easy', 'medium', 'hard'];
  const TYPES = ['open', 'mcq', 'short'];
  const DEFAULT_TIMES = { easy: 60, medium: 120, hard: 180 };
  const DEFAULT_POINTS = { easy: 1, medium: 2, hard: 3 };
  const RING_CIRCUMFERENCE = 2 * Math.PI * 52; // matches r=52 in the SVG

  // ---------- State ----------
  let bank = [];
  let settings = { timeLimits: { ...DEFAULT_TIMES }, points: { ...DEFAULT_POINTS } };
  let session = null;
  let timer = { id: null, remaining: 0, total: 0, startedAt: 0 };
  let pending = null;   // result awaiting self-marking confirmation
  let mcqChoice = null;

  // ---------- DOM helpers ----------
  const $ = (sel) => document.querySelector(sel);
  const $$ = (sel) => [...document.querySelectorAll(sel)];
  const screens = { setup: $('#screen-setup'), quiz: $('#screen-quiz'), results: $('#screen-results') };
  const showScreen = (name) => {
    Object.values(screens).forEach((s) => s.classList.remove('active'));
    screens[name].classList.add('active');
    window.scrollTo({ top: 0 });
  };
  const wait = (ms) => new Promise((r) => setTimeout(r, ms));

  // ---------- Theme ----------
  const themeToggle = $('#theme-toggle');
  const applyTheme = (t) => {
    document.documentElement.dataset.theme = t;
    themeToggle.textContent = t === 'dark' ? '☀️' : '🌙';
    localStorage.setItem('quiz-theme', t);
  };
  applyTheme(localStorage.getItem('quiz-theme') ||
    (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'));
  themeToggle.addEventListener('click', () =>
    applyTheme(document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'));

  // ---------- Loading ----------
  async function loadQuestions() {
    try {
      const res = await fetch('questions.json', { cache: 'no-store' });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      settings.timeLimits = { ...DEFAULT_TIMES, ...(data.settings?.timeLimits || {}) };
      settings.points = { ...DEFAULT_POINTS, ...(data.settings?.points || {}) };

      bank = (data.questions || []).map((q, i) => {
        const difficulty = DIFFICULTIES.includes((q.difficulty || '').toLowerCase()) ? q.difficulty.toLowerCase() : 'medium';
        const type = TYPES.includes(q.type) ? q.type : (q.options?.length ? 'mcq' : (q.markScheme?.length ? 'open' : 'short'));
        return {
          id: q.id ?? i + 1,
          set: q.set || 'Questions',
          parentId: q.parentId || null,
          partLabel: q.partLabel || '',
          topic: q.topic || 'General',
          source: q.source || '',
          difficulty,
          type,
          question: q.question,
          context: Array.isArray(q.context) ? q.context : [],
          options: Array.isArray(q.options) ? q.options : [],
          answers: Array.isArray(q.answers) ? q.answers : (q.answer != null ? [q.answer] : []),
          markScheme: Array.isArray(q.markScheme) ? q.markScheme : [],
          sampleAnswer: q.sampleAnswer || '',
          explanation: q.explanation || '',
          answerDisplay: q.answerDisplay || '',
          tolerance: Number.isFinite(q.tolerance) ? q.tolerance : 0,
          marks: Number.isFinite(q.marks) ? q.marks : settings.points[difficulty],
          timeLimit: q.timeLimit,
        };
      }).filter((q) => q.question);
      buildSetup();
    } catch (err) {
      const msg = $('#setup-error');
      msg.hidden = false;
      msg.innerHTML = `Couldn't load <code>questions.json</code> (${err.message}). ` +
        `If you opened this file directly, serve the folder over HTTP instead, e.g. ` +
        `<code>python3 -m http.server</code> and open <code>http://localhost:8000</code>.`;
      $('#start-btn').disabled = true;
    }
  }

  // ---------- Setup screen ----------
  function buildSetup() {
    const sets = [...new Set(bank.map((q) => q.set))].sort();
    $('#set-list').innerHTML = sets.map((t) => {
      const n = bank.filter((q) => q.set === t).length;
      return `<label class="chip"><input type="checkbox" value="${escapeHtml(t)}" checked /> ${escapeHtml(t)} <small>(${n})</small></label>`;
    }).join('');

    const topics = [...new Set(bank.map((q) => q.topic))].sort();
    $('#topic-list').innerHTML = topics.map((t) => {
      const n = bank.filter((q) => q.topic === t).length;
      return `<label class="chip"><input type="checkbox" value="${escapeHtml(t)}" checked /> ${escapeHtml(t)} <small>(${n})</small></label>`;
    }).join('');

    DIFFICULTIES.forEach((d) => {
      $(`#count-${d}`).textContent = `(${bank.filter((q) => q.difficulty === d).length})`;
      $(`#time-${d}`).value = settings.timeLimits[d];
    });
    TYPES.forEach((t) => {
      const n = bank.filter((q) => q.type === t).length;
      const chip = $(`#type-list input[value="${t}"]`).closest('.chip');
      $(`#count-${t}`).textContent = `(${n})`;
      chip.style.display = n ? '' : 'none';
    });

    $('#num-questions').max = bank.length;
    $('#num-questions').value = Math.min(10, bank.length);

    const best = JSON.parse(localStorage.getItem('quiz-best') || 'null');
    if (best) {
      const el = $('#best-score');
      el.hidden = false;
      el.textContent = `🏆 Best session: ${best.score}/${best.max} marks · ${best.correct}/${best.total} questions · ${best.date}`;
    }
  }

  function readConfig() {
    const checked = (sel) => $$(`${sel} input:checked`).map((i) => i.value);
    const timeLimits = {};
    DIFFICULTIES.forEach((d) => {
      const v = parseInt($(`#time-${d}`).value, 10);
      timeLimits[d] = Number.isFinite(v) && v >= 5 ? v : settings.timeLimits[d];
    });
    return {
      sets: checked('#set-list'),
      topics: checked('#topic-list'),
      difficulties: checked('#difficulty-list'),
      types: checked('#type-list'),
      count: parseInt($('#num-questions').value, 10) || 1,
      order: $('#order').value,
      timeLimits,
    };
  }

  function filterPool(cfg) {
    return bank.filter((q) => cfg.sets.includes(q.set) && cfg.topics.includes(q.topic) && cfg.difficulties.includes(q.difficulty) && cfg.types.includes(q.type));
  }

  $('#start-btn').addEventListener('click', () => {
    const cfg = readConfig();
    const pool = filterPool(cfg);
    const err = $('#setup-error');
    if (!pool.length) {
      err.hidden = false;
      err.textContent = 'No questions match the selected source, topics, difficulties and types.';
      return;
    }
    err.hidden = true;
    startSession(pickQuestions(pool, cfg), cfg);
  });

  function pickQuestions(pool, cfg) {
    let list = [...pool];
    if (cfg.order === 'shuffle') shuffle(list);
    list = list.slice(0, Math.min(cfg.count, list.length));
    if (cfg.order === 'ascending') {
      list.sort((a, b) => DIFFICULTIES.indexOf(a.difficulty) - DIFFICULTIES.indexOf(b.difficulty));
    }
    return list;
  }

  // ---------- Session ----------
  function startSession(questions, cfg) {
    session = { questions, index: 0, results: [], config: cfg, score: 0, maxScore: questions.reduce((s, q) => s + q.marks, 0) };
    $('#q-total').textContent = questions.length;
    $('#live-score').textContent = '0';
    showScreen('quiz');
    showQuestion();
  }

  const currentQuestion = () => session.questions[session.index];

  function showQuestion() {
    const q = currentQuestion();
    const limit = q.timeLimit || session.config.timeLimits[q.difficulty];
    pending = null;
    mcqChoice = null;

    $('#q-index').textContent = session.index + 1;
    $('#progress-fill').style.width = `${(session.index / session.questions.length) * 100}%`;
    $('#q-topic').textContent = q.topic;
    const diffTag = $('#q-difficulty');
    diffTag.textContent = `${q.difficulty} · ${q.marks} mark${q.marks === 1 ? '' : 's'}`;
    diffTag.className = `tag tag-difficulty ${q.difficulty}`;

    $('#q-source').textContent = [q.source, q.partLabel && !q.partLabel.startsWith('MCQ') ? `part ${q.partLabel}` : ''].filter(Boolean).join(' — ');
    const ctx = $('#q-context');
    ctx.hidden = !q.context.length;
    ctx.open = false;
    $('#q-context-list').innerHTML = q.context.map((c) => `<li>${escapeHtml(c)}</li>`).join('');

    $('#q-text').textContent = q.question;

    // input mode
    const input = $('#answer-input'), ta = $('#answer-textarea'), mcq = $('#mcq-options');
    input.hidden = q.type !== 'short';
    ta.hidden = q.type !== 'open';
    mcq.hidden = q.type !== 'mcq';
    input.value = ''; ta.value = '';
    input.disabled = ta.disabled = false;
    if (q.type === 'mcq') {
      mcq.innerHTML = q.options.map((o) =>
        `<button type="button" class="mcq-option" data-letter="${escapeHtml(o.letter)}">
           <span class="mcq-letter">${escapeHtml(o.letter)}</span><span>${escapeHtml(o.text)}</span>
         </button>`).join('');
    }
    $('#submit-btn').disabled = q.type === 'mcq';
    $('#skip-btn').disabled = false;
    $('#answer-form').hidden = false;
    $('#feedback').hidden = true;
    $('#marking').hidden = true;

    $('.timer-ring').className = `timer-ring ${q.difficulty}`;
    startTimer(limit);
    setTimeout(() => (q.type === 'open' ? ta : q.type === 'short' ? input : $('#skip-btn')).focus(), 50);
  }

  // MCQ option selection (delegated)
  $('#mcq-options').addEventListener('click', (e) => {
    const btn = e.target.closest('.mcq-option');
    if (!btn || btn.disabled) return;
    mcqChoice = btn.dataset.letter;
    $$('.mcq-option').forEach((b) => b.classList.toggle('selected', b === btn));
    $('#submit-btn').disabled = false;
  });

  // ---------- Timer ----------
  function startTimer(seconds) {
    stopTimer();
    timer.total = seconds;
    timer.remaining = seconds;
    timer.startedAt = Date.now();
    renderTimer(true);
    timer.id = setInterval(() => {
      const elapsed = Math.floor((Date.now() - timer.startedAt) / 1000);
      timer.remaining = Math.max(0, timer.total - elapsed);
      renderTimer();
      if (timer.remaining <= 0) {
        stopTimer();
        finishQuestion({ timedOut: true });
      }
    }, 250);
  }

  function stopTimer() {
    if (timer.id) clearInterval(timer.id);
    timer.id = null;
  }

  function renderTimer(reset = false) {
    const ringFg = $('#ring-fg'), ring = $('.timer-ring');
    $('#timer-text').textContent = formatTime(timer.remaining);
    const fraction = timer.total ? timer.remaining / timer.total : 0;
    if (reset) {
      ringFg.style.transition = 'none';
      ringFg.style.strokeDashoffset = 0;
      void ringFg.getBoundingClientRect();
      ringFg.style.transition = '';
    } else {
      ringFg.style.strokeDashoffset = RING_CIRCUMFERENCE * (1 - fraction);
    }
    ring.classList.toggle('urgent', timer.remaining <= Math.min(10, timer.total * 0.2) && timer.remaining > 0);
  }

  function formatTime(s) {
    if (s < 60) return String(s);
    return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`;
  }

  // ---------- Answering ----------
  $('#answer-form').addEventListener('submit', (e) => {
    e.preventDefault();
    const q = currentQuestion();
    if (q.type === 'mcq') { if (mcqChoice) finishQuestion({ given: mcqChoice }); return; }
    const given = (q.type === 'open' ? $('#answer-textarea') : $('#answer-input')).value.trim();
    if (!given) return;
    finishQuestion({ given });
  });

  $('#skip-btn').addEventListener('click', () => finishQuestion({ skipped: true }));

  function currentTypedAnswer(q) {
    if (q.type === 'open') return $('#answer-textarea').value.trim();
    if (q.type === 'short') return $('#answer-input').value.trim();
    return mcqChoice || '';
  }

  function finishQuestion({ given, timedOut = false, skipped = false }) {
    stopTimer();
    const q = currentQuestion();
    if (given == null) given = currentTypedAnswer(q); // keep whatever was typed on timeout/skip
    const timeTaken = Math.min(timer.total, Math.round((Date.now() - timer.startedAt) / 10) / 100);

    // lock inputs
    $('#answer-input').disabled = $('#answer-textarea').disabled = true;
    $('#submit-btn').disabled = $('#skip-btn').disabled = true;
    $$('.mcq-option').forEach((b) => { b.disabled = true; });

    const fb = $('#feedback'), title = $('#feedback-title'), body = $('#feedback-body'), marking = $('#marking');
    fb.hidden = false;
    marking.hidden = true;
    body.innerHTML = '';

    const result = { q, given, timedOut, skipped, timeTaken, marksAwarded: 0, marksMax: q.marks, correct: false };

    if (q.type === 'open') {
      // self-marking: show mark scheme, student ticks points earned
      pending = result;
      fb.className = 'feedback pending';
      title.textContent = timedOut ? '⏰ Time\'s up — mark what you wrote' : skipped ? '⏭ Skipped — review the mark scheme' : '📝 Mark your answer';
      const ya = $('#marking-your-answer');
      ya.textContent = given || '(nothing written)';
      ya.classList.toggle('empty', !given);
      $('#mark-scheme-list').innerHTML = q.markScheme.map((m, i) =>
        `<li><label><input type="checkbox" data-i="${i}" ${skipped || !given ? 'disabled' : ''} /> <span>${escapeHtml(m)}</span></label></li>`).join('');
      $('#sample-answer').textContent = q.sampleAnswer || '(no model answer)';
      $('.sample').open = false;
      $('#marks-max').textContent = q.marks;
      $('#marks-awarded').textContent = '0';
      marking.hidden = false;
      $('#next-btn').textContent = 'Confirm marks →';
      setTimeout(() => $('#mark-scheme-list input:not(:disabled)')?.focus(), 30);
      return;
    }

    // auto-marked types
    const correct = !timedOut && !skipped && isCorrect(given, q.answers, q.type, q.tolerance);
    result.correct = correct;
    result.marksAwarded = correct ? q.marks : 0;
    commitResult(result);

    fb.className = `feedback ${correct ? 'correct' : 'wrong'}`;
    if (correct) title.textContent = `✅ Correct! +${q.marks} mark${q.marks === 1 ? '' : 's'}`;
    else if (timedOut) title.textContent = '⏰ Time\'s up!';
    else if (skipped) title.textContent = '⏭ Skipped';
    else title.textContent = '❌ Not quite';

    if (q.type === 'mcq') {
      $$('.mcq-option').forEach((b) => {
        if (q.answers.includes(b.dataset.letter)) b.classList.add('is-correct');
        else if (b.dataset.letter === given) b.classList.add('is-wrong');
      });
    }
    const ansLine = correct ? '' : `Answer: <span class="ans">${escapeHtml(q.answerDisplay || q.answers[0] || '')}</span>`;
    const expl = q.explanation || (q.type === 'mcq' ? q.markScheme.join(' ') : '');
    body.innerHTML = ansLine + (expl ? `<div class="muted">${escapeHtml(expl)}</div>` : '');

    $('#next-btn').textContent = session.index + 1 < session.questions.length ? 'Next question →' : 'See results →';
    setTimeout(() => $('#next-btn').focus(), 30);
  }

  // live total while ticking mark scheme boxes
  $('#mark-scheme-list').addEventListener('change', () => {
    if (!pending) return;
    const ticked = $$('#mark-scheme-list input:checked').length;
    // if the mark scheme has more points than marks, cap at max marks
    $('#marks-awarded').textContent = Math.min(ticked, pending.marksMax);
  });

  function commitResult(result) {
    session.score += result.marksAwarded;
    session.results.push(result);
    $('#live-score').textContent = session.score;
  }

  $('#next-btn').addEventListener('click', nextQuestion);

  document.addEventListener('keydown', (e) => {
    if (e.key !== 'Enter' || !screens.quiz.classList.contains('active') || $('#feedback').hidden) return;
    if (e.target.tagName === 'INPUT' && e.target.type === 'checkbox') return; // let checkbox toggle
    e.preventDefault();
    nextQuestion();
  });

  // Ctrl/Cmd+Enter submits the textarea
  $('#answer-textarea').addEventListener('keydown', (e) => {
    if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {
      e.preventDefault();
      $('#answer-form').requestSubmit();
    }
  });

  function nextQuestion() {
    if (pending) {
      const ticked = $$('#mark-scheme-list input:checked').length;
      pending.marksAwarded = Math.min(ticked, pending.marksMax);
      pending.correct = pending.marksAwarded === pending.marksMax;
      commitResult(pending);
      pending = null;
    }
    session.index += 1;
    if (session.index >= session.questions.length) return showResults();
    showQuestion();
  }

  $('#quit-btn').addEventListener('click', () => {
    stopTimer();
    pending = null;
    if (session.results.length) showResults();
    else showScreen('setup');
  });

  // ---------- Answer checking (short / mcq) ----------
  function normalize(s) {
    return String(s)
      .toLowerCase()
      .replace(/[²]/g, '^2').replace(/[³]/g, '^3').replace(/[⁴]/g, '^4')
      .replace(/[₂]/g, '2').replace(/[₃]/g, '3')
      .replace(/×/g, 'x').replace(/−/g, '-')
      .replace(/^(the|a|an)\s+/, '')
      .replace(/[\s.,;:!?'"()\[\]{}]/g, '')
      .trim();
  }

  // Parse "5.23e-19", "5.23 x 10^-19", "5.23×10⁻¹⁹", "5.23*10^(-19)", "4.8 keV" -> number (first numeric token)
  const SUP = { '⁰': '0', '¹': '1', '²': '2', '³': '3', '⁴': '4', '⁵': '5', '⁶': '6', '⁷': '7', '⁸': '8', '⁹': '9', '⁻': '-', '⁺': '+' };
  function parseNumber(str) {
    let s = String(str).trim()
      .replace(/[⁰¹²³⁴⁵⁶⁷⁸⁹⁻⁺]/g, (c) => SUP[c])
      .replace(/−/g, '-').replace(/[×∗*]/g, 'x').replace(/\s+/g, '')
      .replace(/10\^\(?([-+]?\d+)\)?/g, '10^$1');
    // a x 10^b  |  a x 10b (after superscript conversion)  |  10^b alone
    let m = s.match(/^([-+]?\d*\.?\d+)x10\^?([-+]?\d+)/) || s.match(/^([-+]?\d*\.?\d+)e([-+]?\d+)/i);
    if (m) return parseFloat(m[1]) * Math.pow(10, parseInt(m[2], 10));
    m = s.match(/^10\^([-+]?\d+)/);
    if (m) return Math.pow(10, parseInt(m[1], 10));
    m = s.match(/^([-+]?\d*\.?\d+)/);
    return m ? parseFloat(m[1]) : NaN;
  }

  function isCorrect(given, answers, type, tolerance = 0) {
    if (type === 'mcq') return answers.map((a) => String(a).toUpperCase()).includes(String(given).toUpperCase());
    const g = normalize(given);
    if (!g) return false;
    return answers.some((a) => {
      const n = normalize(a);
      if (n === g) return true;
      const an = parseNumber(a);
      if (Number.isNaN(an)) return false;
      const gn = parseNumber(given);
      if (Number.isNaN(gn)) return false;
      const tol = Math.max(tolerance, 0.005); // always allow rounding to ~3 s.f.
      return Math.abs(gn - an) <= Math.abs(an) * tol + 1e-12;
    });
  }

  // ---------- Results ----------
  function showResults() {
    const r = session.results;
    const total = r.length;
    const maxMarks = r.reduce((s, x) => s + x.marksMax, 0);
    const fullMarks = r.filter((x) => x.correct).length;
    const pct = maxMarks ? Math.round((session.score / maxMarks) * 100) : 0;
    const avg = total ? r.reduce((s, x) => s + x.timeTaken, 0) / total : 0;

    $('#r-score').textContent = `${session.score}/${maxMarks}`;
    $('#r-correct').textContent = `${fullMarks}/${total}`;
    $('#r-accuracy').textContent = `${pct}%`;
    $('#r-avg-time').textContent = `${avg.toFixed(1)}s`;

    $('#breakdown').innerHTML = DIFFICULTIES.map((d) => {
      const rows = r.filter((x) => x.q.difficulty === d);
      if (!rows.length) return '';
      const got = rows.reduce((s, x) => s + x.marksAwarded, 0);
      const max = rows.reduce((s, x) => s + x.marksMax, 0);
      return `<div class="breakdown-row ${d}">
        <div class="label">${d}</div>
        <div class="bar"><div style="width:${max ? (got / max) * 100 : 0}%"></div></div>
        <div class="nums">${got}/${max}</div>
      </div>`;
    }).join('');

    $('#review-list').innerHTML = r.map((x, i) => {
      let status;
      if (x.timedOut) status = 'Timed out';
      else if (x.skipped) status = 'Skipped';
      else if (x.q.type === 'open') status = x.correct ? 'Full marks' : x.marksAwarded ? 'Partial marks' : 'No marks';
      else status = x.correct ? 'Correct' : `You answered "${escapeHtml(x.given)}"`;
      const cls = x.correct ? 'correct' : 'wrong';
      const answerBit = x.q.type !== 'open' && !x.correct ? `<span>Answer: <strong>${escapeHtml(x.q.answerDisplay || x.q.answers[0] || '')}</strong></span>` : '';
      return `<li class="review-item ${cls}">
        <div class="q">${i + 1}. ${escapeHtml(x.q.question.split('\n')[0])}</div>
        <div class="meta">
          <span>${status}</span>
          <span><strong>${x.marksAwarded}/${x.marksMax}</strong> marks</span>
          ${answerBit}
          <span>${x.q.topic}</span>
          <span>${x.q.difficulty}</span>
          <span>${x.timeTaken.toFixed(1)}s</span>
        </div>
      </li>`;
    }).join('');

    $('#retry-wrong-btn').disabled = fullMarks === total;

    const best = JSON.parse(localStorage.getItem('quiz-best') || 'null');
    if (!best || session.score > best.score) {
      localStorage.setItem('quiz-best', JSON.stringify({
        score: session.score, max: maxMarks, correct: fullMarks, total, date: new Date().toLocaleDateString(),
      }));
    }
    showScreen('results');
  }

  $('#retry-btn').addEventListener('click', () => {
    const cfg = session.config;
    startSession(pickQuestions(filterPool(cfg), cfg), cfg);
  });

  $('#retry-wrong-btn').addEventListener('click', () => {
    const wrong = session.results.filter((x) => !x.correct).map((x) => x.q);
    if (!wrong.length) return;
    startSession(shuffle([...wrong]), session.config);
  });

  $('#home-btn').addEventListener('click', () => { buildSetup(); showScreen('setup'); });

  // ---------- Utils ----------
  function shuffle(arr) {
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
  }

  function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  }

  loadQuestions();
})();
